# Copyright lowRISC contributors.
# Copyright 2025 MHX™ Neural.
# Licensed under the Apache License, Version 2.0, see LICENSE for details.
# SPDX-License-Identifier: Apache-2.0

# MLPerfTiny Benchmark Makefile for MHX™ Ternary Extensions

PROGRAM = mlperftiny_bench
PROGRAM_DIR := $(dir $(abspath $(lastword $(MAKEFILE_LIST))))

include $(PROGRAM_DIR)/../common/common.mk
