# Copyright lowRISC contributors.
# Copyright 2025 MHX™ Neural.
# Licensed under the Apache License, Version 2.0, see LICENSE for details.
# SPDX-License-Identifier: Apache-2.0

.PHONY: lint
lint:
	mypy --config-file ../mypy.ini --strict ./sv2v_in_place.py
