#!/usr/bin/env bash
# Copyright lowRISC contributors.
# Copyright 2025 MHX™ Neural.
# Licensed under the Apache License, Version 2.0, see LICENSE for details.
# SPDX-License-Identifier: Apache-2.0

################################################################################
# Formal Verification Script for MHX™ Ternary Extensions
#
# This script runs formal verification on the MHX™ ternary components using
# either JasperGold or VC Formal (Synopsys).
#
# Usage:
#   ./ci/run-formal-verification.sh [--tool jasper|vcformal] [--module MODULE]
#
# Environment variables:
#   FORMAL_TOOL    - Tool to use (jasper or vcformal, default: jasper)
#   RTL_ROOT       - Root directory of RTL files (default: rtl/)
#   FORMAL_RESULTS - Output directory for results (default: formal_results/)
#   TIMEOUT        - Maximum runtime per module in minutes (default: 60)
################################################################################

set -e
set -o pipefail

# Script configuration
SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
REPO_ROOT="$(cd "${SCRIPT_DIR}/.." && pwd)"
RTL_ROOT="${RTL_ROOT:-${REPO_ROOT}/rtl}"
FORMAL_RESULTS="${FORMAL_RESULTS:-${REPO_ROOT}/formal_results}"
FORMAL_TOOL="${FORMAL_TOOL:-jasper}"
TIMEOUT="${TIMEOUT:-60}"

# Color codes for output
RED='\033[0;31m'
GREEN='\033[0;32m'
YELLOW='\033[1;33m'
BLUE='\033[0;34m'
NC='\033[0m' # No Color

# Logging functions
log_info() {
    echo -e "${BLUE}[INFO]${NC} $*"
}

log_success() {
    echo -e "${GREEN}[SUCCESS]${NC} $*"
}

log_warning() {
    echo -e "${YELLOW}[WARNING]${NC} $*"
}

log_error() {
    echo -e "${RED}[ERROR]${NC} $*"
}

# Parse command line arguments
MODULE=""
while [[ $# -gt 0 ]]; do
    case $1 in
        --tool)
            FORMAL_TOOL="$2"
            shift 2
            ;;
        --module)
            MODULE="$2"
            shift 2
            ;;
        --help)
            echo "Usage: $0 [--tool jasper|vcformal] [--module MODULE]"
            echo ""
            echo "Options:"
            echo "  --tool     Formal verification tool (jasper or vcformal)"
            echo "  --module   Specific module to verify (default: all)"
            echo "  --help     Show this help message"
            exit 0
            ;;
        *)
            log_error "Unknown option: $1"
            exit 1
            ;;
    esac
done

# Modules to verify
MODULES=(
    "ibex_ternary_alu"
    "ibex_ternary_regfile"
    "ibex_neural_unit"
)

# If specific module requested, verify only that
if [[ -n "$MODULE" ]]; then
    MODULES=("$MODULE")
fi

# Create results directory
mkdir -p "$FORMAL_RESULTS"

# Check if formal tool is available
check_tool() {
    case "$FORMAL_TOOL" in
        jasper)
            if ! command -v jaspergold &> /dev/null; then
                log_error "JasperGold not found. Please set up Cadence JasperGold."
                exit 1
            fi
            log_info "Using Cadence JasperGold for formal verification"
            ;;
        vcformal)
            if ! command -v vc_formal &> /dev/null; then
                log_error "VC Formal not found. Please set up Synopsys VC Formal."
                exit 1
            fi
            log_info "Using Synopsys VC Formal for formal verification"
            ;;
        *)
            log_error "Unsupported formal tool: $FORMAL_TOOL"
            log_error "Supported tools: jasper, vcformal"
            exit 1
            ;;
    esac
}

# Generate JasperGold TCL script
generate_jasper_tcl() {
    local module=$1
    local tcl_file="${FORMAL_RESULTS}/${module}_jasper.tcl"

    cat > "$tcl_file" <<EOF
# JasperGold TCL script for ${module}
# Auto-generated by run-formal-verification.sh

# Set up analysis
clear -all

# Read design files
analyze -sv12 \\
    ${RTL_ROOT}/ibex_pkg.sv \\
    ${RTL_ROOT}/${module}.sv

# Elaborate design
elaborate -top ${module}

# Set up clock and reset
if {[info exists clk_i]} {
    clock clk_i
    reset -expression {!rst_ni}
}

# Configure formal verification
set_prove_time_limit ${TIMEOUT}m
set_engine_mode {Hp Ht B I N}

# Prove all assertions
prove -bg -all

# Generate reports
report -results -file ${FORMAL_RESULTS}/${module}_results.txt
report -summary -file ${FORMAL_RESULTS}/${module}_summary.txt

# Check results
set num_proven [get_property -value proven [get_assertions]]
set num_failed [get_property -value failing [get_assertions]]
set num_total [llength [get_assertions]]

puts "========================================"
puts "Formal Verification Results for ${module}"
puts "========================================"
puts "Total assertions: \$num_total"
puts "Proven: \$num_proven"
puts "Failed: \$num_failed"
puts "========================================"

if {\$num_failed > 0} {
    puts "ERROR: Some assertions failed!"
    exit 1
} else {
    puts "SUCCESS: All assertions proven!"
    exit 0
}
EOF

    echo "$tcl_file"
}

# Generate VC Formal TCL script
generate_vcformal_tcl() {
    local module=$1
    local tcl_file="${FORMAL_RESULTS}/${module}_vcformal.tcl"

    cat > "$tcl_file" <<EOF
# VC Formal TCL script for ${module}
# Auto-generated by run-formal-verification.sh

# Read design files
read_file -format sverilog \\
    ${RTL_ROOT}/ibex_pkg.sv \\
    ${RTL_ROOT}/${module}.sv

# Set top module
set_top ${module}

# Configure formal verification
set_fml_appmode FPV
set_fml_engine_mode {Hp Ht B}

# Set timeout
set_fml_time_limit ${TIMEOUT}m

# Run formal verification
check_fv -init_phase 10 -block

# Generate report
report_fv -summary -file ${FORMAL_RESULTS}/${module}_summary.txt
report_fv -detailed -file ${FORMAL_RESULTS}/${module}_detailed.txt

# Check for failures
set failures [get_fv_result -failing]
if {[llength \$failures] > 0} {
    puts "ERROR: Found failing assertions in ${module}"
    exit 1
} else {
    puts "SUCCESS: All assertions proven in ${module}"
    exit 0
}
EOF

    echo "$tcl_file"
}

# Run formal verification on a module
verify_module() {
    local module=$1
    local start_time=$(date +%s)

    log_info "Starting formal verification of ${module}..."

    case "$FORMAL_TOOL" in
        jasper)
            local tcl_file=$(generate_jasper_tcl "$module")
            local log_file="${FORMAL_RESULTS}/${module}_jasper.log"

            if timeout "${TIMEOUT}m" jaspergold -tcl "$tcl_file" > "$log_file" 2>&1; then
                log_success "${module}: Formal verification PASSED"
                return 0
            else
                local exit_code=$?
                if [ $exit_code -eq 124 ]; then
                    log_error "${module}: Formal verification TIMEOUT after ${TIMEOUT} minutes"
                else
                    log_error "${module}: Formal verification FAILED (see ${log_file})"
                fi
                return 1
            fi
            ;;
        vcformal)
            local tcl_file=$(generate_vcformal_tcl "$module")
            local log_file="${FORMAL_RESULTS}/${module}_vcformal.log"

            if timeout "${TIMEOUT}m" vc_formal -f "$tcl_file" > "$log_file" 2>&1; then
                log_success "${module}: Formal verification PASSED"
                return 0
            else
                local exit_code=$?
                if [ $exit_code -eq 124 ]; then
                    log_error "${module}: Formal verification TIMEOUT after ${TIMEOUT} minutes"
                else
                    log_error "${module}: Formal verification FAILED (see ${log_file})"
                fi
                return 1
            fi
            ;;
    esac

    local end_time=$(date +%s)
    local duration=$((end_time - start_time))
    log_info "${module}: Verification took ${duration} seconds"
}

################################################################################
# Main execution
################################################################################

log_info "========================================"
log_info "MHX™ Ternary Formal Verification Suite"
log_info "========================================"
log_info "Tool: ${FORMAL_TOOL}"
log_info "RTL Root: ${RTL_ROOT}"
log_info "Results: ${FORMAL_RESULTS}"
log_info "Timeout: ${TIMEOUT} minutes per module"
log_info "Modules: ${MODULES[*]}"
log_info "========================================"

# Check if tool is available
check_tool

# Track results
total_modules=${#MODULES[@]}
passed_modules=0
failed_modules=0
failed_module_list=()

# Run verification on each module
for module in "${MODULES[@]}"; do
    if verify_module "$module"; then
        ((passed_modules++))
    else
        ((failed_modules++))
        failed_module_list+=("$module")
    fi
    echo ""
done

# Final summary
log_info "========================================"
log_info "Formal Verification Summary"
log_info "========================================"
log_info "Total modules: ${total_modules}"
log_success "Passed: ${passed_modules}"
if [ $failed_modules -gt 0 ]; then
    log_error "Failed: ${failed_modules}"
    log_error "Failed modules: ${failed_module_list[*]}"
else
    log_success "Failed: 0"
fi
log_info "Results directory: ${FORMAL_RESULTS}"
log_info "========================================"

# Exit with appropriate code
if [ $failed_modules -eq 0 ]; then
    log_success "✓ All formal verification checks PASSED"
    exit 0
else
    log_error "✗ Some formal verification checks FAILED"
    exit 1
fi
